### ISSUE TITLE
I got pydantic error

### ISSUE THREAD

**Issue by syyunn** [gh18l/CrawlGPT#2]
I got the following error when I run `python pipeline.py > output.txt`.

Traceback (most recent call last):
  File "/Users/syyun/Dropbox (MIT)/CrawlGPT/pipeline.py", line 11, in <module>
    from langchain import PromptTemplate, OpenAI, LLMChain
  File "/Users/syyun/Dropbox (MIT)/CrawlGPT/langchain/__init__.py", line 6, in <module>
    from langchain.agents import MRKLChain, ReActChain, SelfAskWithSearchChain
  File "/Users/syyun/Dropbox (MIT)/CrawlGPT/langchain/agents/__init__.py", line 2, in <module>
    from langchain.agents.agent import (
  File "/Users/syyun/Dropbox (MIT)/CrawlGPT/langchain/agents/agent.py", line 16, in <module>
    from langchain.agents.tools import InvalidTool
  File "/Users/syyun/Dropbox (MIT)/CrawlGPT/langchain/agents/tools.py", line 4, in <module>
    from langchain.callbacks.manager import (
  File "/Users/syyun/Dropbox (MIT)/CrawlGPT/langchain/callbacks/__init__.py", line 3, in <module>
    from langchain.callbacks.aim_callback import AimCallbackHandler
  File "/Users/syyun/Dropbox (MIT)/CrawlGPT/langchain/callbacks/aim_callback.py", line 4, in <module>
    from langchain.callbacks.base import BaseCallbackHandler
  File "/Users/syyun/Dropbox (MIT)/CrawlGPT/langchain/callbacks/base.py", line 7, in <module>
    from langchain.schema import (
  File "/Users/syyun/Dropbox (MIT)/CrawlGPT/langchain/schema.py", line 151, in <module>
    class ChatGeneration(Generation):
  File "/Users/syyun/anaconda3/envs/crawlgpt/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 98, in __new__
    private_attributes = inspect_namespace(
                         ^^^^^^^^^^^^^^^^^^
  File "/Users/syyun/anaconda3/envs/crawlgpt/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 342, in inspect_namespace
    raise PydanticUserError(
pydantic.errors.PydanticUserError: Field 'text' defined on a base class was overridden by a non-annotated attribute. All field definitions, including overrides, require a type annotation.

For further information visit https://errors.pydantic.dev/2.3/u/model-field-overridden

**Comment by gh18l** [comment]
I haven't encountered this error before, but the answer GPT-4 gave me was:

> The error message suggests that there's a problem with Pydantic model definition. Specifically, it appears that a field named text was defined in a base class and then overridden in a subclass without type annotation.
> 
> Let's break down the key parts of the error message:
> 
> 1. `Field 'text' defined on a base class was overridden by a non-annotated attribute.`: This means that a base class has a field named `text` with a type annotation, but a subclass has overridden this field without providing a type annotation.
> 
> 2. `All field definitions, including overrides, require a type annotation.`: Pydantic models require that all fields, even those that override fields in a base class, have type annotations.
> 
> Here's how you might solve the problem:
> 
> ### Option 1: Add Type Annotations to Subclass Field
> If the `text` field is being overridden in a subclass, you should provide a type annotation for it, similar to how it was annotated in the base class. For example:
> 
> ```python
> from pydantic import BaseModel
> 
> class BaseClass(BaseModel):
>     text: str
> 
> class SubClass(BaseClass):
>     text: str  # <-- Add type annotation here
> ```
> 
> ### Option 2: Remove Unnecessary Override
> If the subclass doesn't need to override the field, you can simply remove the field from the subclass.
> 
> ### Option 3: Check for Typo or Unintended Override
> Sometimes, a field might be overridden by mistake, due to a typo or copy-paste error. Make sure that the override is actually intended.
> 
> ### Option 4: Update Pydantic
> Though less likely, the issue might be related to a bug or compatibility problem with Pydantic. You can try updating Pydantic to the latest version and see if the problem persists.
> 
> After making one of these changes, try running your code again to see if the problem is resolved.

It seems you need to add a type annotation like `text: str` to the subclass in the file `"/Users/syyun/Dropbox (MIT)/CrawlGPT/langchain/schema.py", line 151, in
class ChatGeneration(Generation)`

**Comment by cnkailyn** [comment]
Downgrade the langchain==0.0.261 is fine for me.
